//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dec_21_ASP_Bikes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CycleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CycleDetail()
        {
            this.RequestCycles = new HashSet<RequestCycle>();
        }
    
        public int CycleID { get; set; }
        public byte[] CycleImage { get; set; }
        public string CycleAccessories { get; set; }
        public string CycleType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestCycle> RequestCycles { get; set; }
    }
}
