//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dec_21_ASP_Bikes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CycleRequestedByUser
    {
        public int UserRequest { get; set; }
        public int RequestID { get; set; }
        public int CycleID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Username { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    
        public virtual RequestCycle RequestCycle { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
