//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dec_21_ASP_Bikes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BikesEntities1 : DbContext
    {
        public BikesEntities1()
            : base("name=BikesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CycleDetail> CycleDetails { get; set; }
        public virtual DbSet<CycleRequestedByUser> CycleRequestedByUsers { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<RequestCycle> RequestCycles { get; set; }
        public virtual DbSet<RegistrationAndCycleRequestedByUser> RegistrationAndCycleRequestedByUsers { get; set; }
    
        public virtual ObjectResult<GetUserDetails_Result> GetUserDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserDetails_Result>("GetUserDetails");
        }
    }
}
