//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dec_21_ASP_Bikes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationAndCycleRequestedByUser
    {
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int UserRequest { get; set; }
        public string Username { get; set; }
        public string Fullname { get; set; }
    }
}
